# Generated by Django 3.1 on 2022-09-05 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20220904_0758'),
        ('cart', '0005_auto_20220903_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='variations',
            field=models.ManyToManyField(to='store.VariationProduct'),
        ),
    ]
