# Generated by Django 3.1 on 2022-09-05 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20220904_0758'),
        ('cart', '0006_cartitem_variations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='variations',
            field=models.ManyToManyField(related_name='variations', to='store.VariationProduct'),
        ),
    ]
